[package]
name = "worldcrier"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = "0.12.5"
tokio = { version = "1.52.3", features = ["full"]}
sqlx = { version = "0.9", features = [ "runtime-tokio", "sqlite", "migrate" ] }
quick-xml = { version = "0.41.0", features = ["serialize", "encoding"] }
reqwest = "0.13.4"
anyhow = "1.0.103"
serde = "1.0.228"
chrono = "0.4.45"
bytes = "1.12.1"
dotenvy = "0.15.7"
lazy_static = "1.5.0"
poise = "0.6.2"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features=["env-filter"]}
rand = "0.10.2"
