[package]
name = "worldcrier"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = "0.12.5"
tokio = { version = "1.52.3", features = ["full"]}
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite", "migrate" ] }
quick-xml = { version = "0.41.0", features = ["serialize", "encoding"] }
reqwest = "0.13.4"
anyhow = "1.0.103"
serde = "1.0.228"
chrono = "0.4.45"
bytes = "1.12.1"
log = "0.4.33"
simplelog = "0.12.2"